<?php
use App\Http\Controllers\Api\AppointmentController;
use App\Http\Controllers\Api\AppointmentOperationsController;
use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\ClinicDayController;
use App\Http\Controllers\Api\CountyController;
use App\Http\Controllers\Api\DoctorController;
use App\Http\Controllers\Api\DoctorFollowController;
use App\Http\Controllers\Api\DoctorWorkspaceController;
use App\Http\Controllers\Api\FacilityController;
use App\Http\Controllers\Api\FacilityWorkspaceController;
use App\Http\Controllers\Api\FinanceController;
use App\Http\Controllers\Api\MpesaController;
use App\Http\Controllers\Api\NotificationController;
use App\Http\Controllers\Api\PaymentController;
use App\Http\Controllers\Api\PatientDiscoveryController;
use App\Http\Controllers\Api\SessionController;
use App\Http\Controllers\Api\SessionSlotController;
use App\Http\Controllers\Api\SpecialtyController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

Route::middleware("auth:sanctum")->get("/user", fn (Request $r) => $r->user());

Route::get("/specialties", [SpecialtyController::class, "index"]);
Route::get("/counties", [CountyController::class, "index"]);
Route::get("/facilities", [FacilityController::class, "index"]);
Route::get("/facilities/{slug}", [FacilityController::class, "show"]);
Route::get("/doctors", [DoctorController::class, "index"]);
Route::get("/doctors/{slug}", [DoctorController::class, "show"]);
Route::get("/doctors/{id}/sessions", [DoctorController::class, "sessions"]);
Route::get("/doctors/{id}/availability", [SessionController::class, "doctorAvailability"]);
Route::get("/doctors/search", [PatientDiscoveryController::class, "search"]);
Route::get("/doctors/{slug}/profile", [PatientDiscoveryController::class, "profile"]);
Route::get("/doctors/{slug}/sessions", [PatientDiscoveryController::class, "sessions"]);
Route::get("/sessions/search", [SessionController::class, "search"]);
Route::get("/sessions/{id}", [PatientDiscoveryController::class, "showSession"]);
Route::get("/sessions/{id}/slots", [SessionSlotController::class, "index"]);
Route::post("/auth/login", [AuthController::class, "login"]);
Route::post("/auth/register", [AuthController::class, "register"]);

Route::middleware("auth:sanctum")->group(function () {
    Route::get("/auth/me", [AuthController::class, "me"]);
    Route::post("/auth/logout", [AuthController::class, "logout"]);
    Route::get("/appointments", [AppointmentController::class, "index"]);
    Route::get("/appointments/{id}", [AppointmentController::class, "show"]);
    Route::post("/appointments", [AppointmentController::class, "store"]);
    Route::patch("/appointments/{id}", [AppointmentController::class, "update"]);
    Route::delete("/appointments/{id}", [AppointmentController::class, "destroy"]);
    Route::post("/appointments/{appointment}/check-in", [AppointmentOperationsController::class, "checkIn"]);
    Route::post("/appointments/{appointment}/start", [AppointmentOperationsController::class, "startConsultation"]);
    Route::post("/appointments/{appointment}/complete", [AppointmentOperationsController::class, "completeConsultation"]);
    Route::post("/appointments/{appointment}/no-show", [AppointmentOperationsController::class, "markNoShow"]);
    Route::post("/appointments/{appointment}/patient-cancel", [AppointmentOperationsController::class, "patientCancel"]);
    Route::post("/appointments/{appointment}/doctor-cancel", [AppointmentOperationsController::class, "doctorCancel"]);
    Route::post("/appointments/{appointment}/facility-cancel", [AppointmentOperationsController::class, "facilityCancel"]);
    Route::post("/appointments/{appointment}/reschedule", [AppointmentOperationsController::class, "reschedule"]);
    Route::post("/payments/initiate", [PaymentController::class, "initiate"]);
    Route::get("/payments/{id}", [PaymentController::class, "show"]);
    Route::get("/v1/mpesa/stk/status/{paymentId}", [MpesaController::class, "stkStatus"]);
    Route::post("/doctors/{id}/follow", [DoctorFollowController::class, "follow"]);
    Route::delete("/doctors/{id}/follow", [DoctorFollowController::class, "unfollow"]);
    Route::get("/notifications", [NotificationController::class, "index"]);
    Route::patch("/notifications/{id}/read", [NotificationController::class, "markRead"]);
    Route::get("/clinic-day", [ClinicDayController::class, "today"]);
    Route::get("/clinic-day/{date}", [ClinicDayController::class, "show"]);
    Route::get("/sessions", [SessionController::class, "index"]);
    Route::post("/sessions", [SessionController::class, "store"]);
    Route::patch("/sessions/{id}", [SessionController::class, "update"]);
    Route::delete("/sessions/{id}", [SessionController::class, "destroy"]);
    Route::post("/sessions/{id}/confirm", [SessionController::class, "confirm"]);
    Route::post("/sessions/{id}/cancel", [SessionController::class, "cancel"]);
    Route::post("/sessions/{id}/restore", [SessionController::class, "restore"]);
    Route::get("/sessions/{session}/slots", [SessionSlotController::class, "index"]);
    Route::get("/schedule", [DoctorWorkspaceController::class, "schedule"]);
    Route::get("/schedule/weekly", [DoctorWorkspaceController::class, "weeklySchedule"]);
    Route::get("/me/doctor-profile", [DoctorWorkspaceController::class, "myDoctorProfile"]);
    Route::get("/me/facilities", [DoctorWorkspaceController::class, "myFacilities"]);
    Route::get("/me/dashboard", [DoctorWorkspaceController::class, "dashboard"]);
    Route::get("/me/today-clinic", [DoctorWorkspaceController::class, "todayClinic"]);
    Route::get("/me/appointments", [DoctorWorkspaceController::class, "appointments"]);
    Route::get("/facility/dashboard", [FacilityWorkspaceController::class, "dashboard"]);
    Route::get("/facility/today-doctors", [FacilityWorkspaceController::class, "todayDoctors"]);
    Route::get("/facility/appointments", [FacilityWorkspaceController::class, "appointments"]);
    Route::get("/facility/doctors", [FacilityWorkspaceController::class, "doctors"]);
    Route::get("/facility/sessions", [FacilityWorkspaceController::class, "facilitySessions"]);
    Route::get("/finance/earnings", [FinanceController::class, "earnings"]);
    Route::get("/finance/payouts", [FinanceController::class, "doctorPayouts"]);
    Route::post("/finance/payout-request", [FinanceController::class, "requestPayout"]);
});

Route::middleware(["auth:sanctum", "ensure.super.admin"])->group(function () {
    Route::get("/admin/finance/marketplace", [FinanceController::class, "marketplace"]);
    Route::get("/admin/finance/payments", [FinanceController::class, "payments"]);
    Route::get("/admin/finance/plans", [FinanceController::class, "plans"]);
    Route::get("/admin/finance/payouts", [FinanceController::class, "adminPayouts"]);
    Route::post("/admin/finance/payouts/{id}/approve", [FinanceController::class, "approvePayout"]);
    Route::post("/admin/finance/payouts/{id}/reject", [FinanceController::class, "rejectPayout"]);
    Route::post("/admin/finance/payouts/{id}/cancel", [FinanceController::class, "cancelPayout"]);
    Route::get("/audit/logs", [\App\Http\Controllers\Api\SuperAdmin\SuperAdminDashboardController::class, "auditLogs"]);
    Route::post("/doctors/{doctor}/reject", [\App\Http\Controllers\Api\SuperAdmin\SuperAdminDashboardController::class, "rejectDoctor"]);
    Route::post("/doctors/{doctor}/suspend", [\App\Http\Controllers\Api\SuperAdmin\SuperAdminDashboardController::class, "suspendDoctor"]);
    Route::post("/facilities/{facility}/reject", [\App\Http\Controllers\Api\SuperAdmin\SuperAdminDashboardController::class, "rejectFacility"]);
    Route::post("/facilities/{facility}/suspend", [\App\Http\Controllers\Api\SuperAdmin\SuperAdminDashboardController::class, "suspendFacility"]);
});

Route::post("/payments/callback", [PaymentController::class, "callback"]);
Route::post("/payments/simulate", [PaymentController::class, "simulate"]);
Route::prefix("v1/mpesa")->group(function () {
    Route::post("/stk/result", [MpesaController::class, "stkResult"]);
    Route::post("/stk/timeout", [MpesaController::class, "stkTimeout"]);
    Route::post("/b2c/result", [MpesaController::class, "b2cResult"]);
});
